version: 0.2

phases:
  install:
    commands:
      - echo Entered the install phase...
      - curl -L -o sbt.deb http://dl.bintray.com/sbt/debian/sbt-0.13.15.deb
      - dpkg -i sbt.deb
      - apt-get update -y
      - apt-get install sbt
  pre_build:
    commands:
      - echo Entered the pre_build phase...
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - ./deploy.sh
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`
artifacts:
  files:
    - ./deploy/*
